export interface SnippetTemplate {
	title: string;
	prefixLines: string[];
	typedBlock: string;
	suffixLines: string[];
}

export interface LanguageSnippetPack {
	key: string;
	label: string;
	languageId: string;
	extension: string;
	workspaceExtensions: string[];
	snippets: SnippetTemplate[];
}

interface RawAlgorithmSnippet {
	title: string;
	code: string;
}

export const LANGUAGE_SNIPPET_PACKS: LanguageSnippetPack[] = [
	createPack('typescript', 'TypeScript', 'typescript', '.ts', ['ts', 'tsx'], [
		{
			title: 'Binary Search',
			code: [
				'function binarySearch(sorted: number[], target: number): number {',
				'\tlet left = 0;',
				'\tlet right = sorted.length - 1;',
				'',
				'\twhile (left <= right) {',
				'\t\tconst mid = left + Math.floor((right - left) / 2);',
				'\t\tif (sorted[mid] === target) {',
				'\t\t\treturn mid;',
				'\t\t}',
				'\t\tif (sorted[mid] < target) {',
				'\t\t\tleft = mid + 1;',
				'\t\t} else {',
				'\t\t\tright = mid - 1;',
				'\t\t}',
				'\t}',
				'',
				'\treturn -1;',
				'}',
			].join('\n'),
		},
		{
			title: 'Quick Sort',
			code: [
				'function quickSort(values: number[]): number[] {',
				'\tif (values.length <= 1) {',
				'\t\treturn values;',
				'\t}',
				'',
				'\tconst pivot = values[values.length - 1];',
				'\tconst left: number[] = [];',
				'\tconst right: number[] = [];',
				'',
				'\tfor (let i = 0; i < values.length - 1; i += 1) {',
				'\t\tif (values[i] <= pivot) {',
				'\t\t\tleft.push(values[i]);',
				'\t\t} else {',
				'\t\t\tright.push(values[i]);',
				'\t\t}',
				'\t}',
				'',
				'\treturn [...quickSort(left), pivot, ...quickSort(right)];',
				'}',
			].join('\n'),
		},
		{
			title: 'Breadth-First Search',
			code: [
				'function bfsShortestPath(graph: Map<string, string[]>, start: string, goal: string): string[] {',
				'\tconst queue: string[] = [start];',
				'\tconst previous = new Map<string, string | null>();',
				'\tprevious.set(start, null);',
				'',
				'\tfor (let head = 0; head < queue.length; head += 1) {',
				'\t\tconst node = queue[head];',
				'\t\tif (node === goal) {',
				'\t\t\tbreak;',
				'\t\t}',
				'',
				'\t\tfor (const neighbor of graph.get(node) ?? []) {',
				'\t\t\tif (previous.has(neighbor)) {',
				'\t\t\t\tcontinue;',
				'\t\t\t}',
				'\t\t\tprevious.set(neighbor, node);',
				'\t\t\tqueue.push(neighbor);',
				'\t\t}',
				'\t}',
				'',
				'\tif (!previous.has(goal)) {',
				'\t\treturn [];',
				'\t}',
				'',
				'\tconst path: string[] = [];',
				'\tfor (let at: string | null = goal; at !== null; at = previous.get(at) ?? null) {',
				'\t\tpath.push(at);',
				'\t}',
				'\tpath.reverse();',
				'\treturn path;',
				'}',
			].join('\n'),
		},
	]),
	createPack('javascript', 'JavaScript', 'javascript', '.js', ['js', 'jsx', 'mjs', 'cjs'], [
		{
			title: 'Binary Search',
			code: [
				'function binarySearch(sorted, target) {',
				'\tlet left = 0;',
				'\tlet right = sorted.length - 1;',
				'',
				'\twhile (left <= right) {',
				'\t\tconst mid = left + Math.floor((right - left) / 2);',
				'\t\tif (sorted[mid] === target) { return mid; }',
				'\t\tif (sorted[mid] < target) { left = mid + 1; }',
				'\t\telse { right = mid - 1; }',
				'\t}',
				'',
				'\treturn -1;',
				'}',
			].join('\n'),
		},
		{
			title: 'Quick Sort',
			code: [
				'function quickSort(values) {',
				'\tif (values.length <= 1) { return values; }',
				'',
				'\tconst pivot = values[values.length - 1];',
				'\tconst left = [];',
				'\tconst right = [];',
				'',
				'\tfor (let i = 0; i < values.length - 1; i += 1) {',
				'\t\tif (values[i] <= pivot) { left.push(values[i]); }',
				'\t\telse { right.push(values[i]); }',
				'\t}',
				'',
				'\treturn [...quickSort(left), pivot, ...quickSort(right)];',
				'}',
			].join('\n'),
		},
		{
			title: 'Breadth-First Search',
			code: [
				'function bfsShortestPath(graph, start, goal) {',
				'\tconst queue = [start];',
				'\tconst previous = new Map([[start, null]]);',
				'',
				'\tfor (let head = 0; head < queue.length; head += 1) {',
				'\t\tconst node = queue[head];',
				'\t\tif (node === goal) { break; }',
				'',
				'\t\tfor (const neighbor of graph.get(node) ?? []) {',
				'\t\t\tif (previous.has(neighbor)) { continue; }',
				'\t\t\tprevious.set(neighbor, node);',
				'\t\t\tqueue.push(neighbor);',
				'\t\t}',
				'\t}',
				'',
				'\tif (!previous.has(goal)) { return []; }',
				'',
				'\tconst path = [];',
				'\tfor (let at = goal; at !== null; at = previous.get(at) ?? null) {',
				'\t\tpath.push(at);',
				'\t}',
				'\tpath.reverse();',
				'\treturn path;',
				'}',
			].join('\n'),
		},
	]),
	createPack('python', 'Python', 'python', '.py', ['py'], [
		{
			title: 'Binary Search',
			code: [
				'def binary_search(sorted_values: list[int], target: int) -> int:',
				'    left, right = 0, len(sorted_values) - 1',
				'    while left <= right:',
				'        mid = left + (right - left) // 2',
				'        if sorted_values[mid] == target:',
				'            return mid',
				'        if sorted_values[mid] < target:',
				'            left = mid + 1',
				'        else:',
				'            right = mid - 1',
				'    return -1',
			].join('\n'),
		},
		{
			title: 'Quick Sort',
			code: [
				'def quick_sort(values: list[int]) -> list[int]:',
				'    if len(values) <= 1:',
				'        return values',
				'',
				'    pivot = values[-1]',
				'    left = [value for value in values[:-1] if value <= pivot]',
				'    right = [value for value in values[:-1] if value > pivot]',
				'    return quick_sort(left) + [pivot] + quick_sort(right)',
			].join('\n'),
		},
		{
			title: 'Breadth-First Search',
			code: [
				'def bfs_shortest_path(graph: dict[str, list[str]], start: str, goal: str) -> list[str]:',
				'    queue: list[str] = [start]',
				'    previous: dict[str, str | None] = {start: None}',
				'    head = 0',
				'',
				'    while head < len(queue):',
				'        node = queue[head]',
				'        head += 1',
				'        if node == goal:',
				'            break',
				'',
				'        for neighbor in graph.get(node, []):',
				'            if neighbor in previous:',
				'                continue',
				'            previous[neighbor] = node',
				'            queue.append(neighbor)',
				'',
				'    if goal not in previous:',
				'        return []',
				'',
				'    path: list[str] = []',
				'    current: str | None = goal',
				'    while current is not None:',
				'        path.append(current)',
				'        current = previous[current]',
				'    path.reverse()',
				'    return path',
			].join('\n'),
		},
	]),
	createPack('java', 'Java', 'java', '.java', ['java'], [
		{
			title: 'Binary Search',
			code: [
				'private static int binarySearch(int[] sorted, int target) {',
				'\tint left = 0;',
				'\tint right = sorted.length - 1;',
				'',
				'\twhile (left <= right) {',
				'\t\tint mid = left + (right - left) / 2;',
				'\t\tif (sorted[mid] == target) {',
				'\t\t\treturn mid;',
				'\t\t}',
				'\t\tif (sorted[mid] < target) {',
				'\t\t\tleft = mid + 1;',
				'\t\t} else {',
				'\t\t\tright = mid - 1;',
				'\t\t}',
				'\t}',
				'',
				'\treturn -1;',
				'}',
			].join('\n'),
		},
		{
			title: 'Sieve of Eratosthenes',
			code: [
				'private static List<Integer> sieveOfEratosthenes(int limit) {',
				'\tboolean[] prime = new boolean[limit + 1];',
				'\tArrays.fill(prime, true);',
				'\tif (limit >= 0) { prime[0] = false; }',
				'\tif (limit >= 1) { prime[1] = false; }',
				'',
				'\tfor (int value = 2; value * value <= limit; value += 1) {',
				'\t\tif (!prime[value]) {',
				'\t\t\tcontinue;',
				'\t\t}',
				'\t\tfor (int multiple = value * value; multiple <= limit; multiple += value) {',
				'\t\t\tprime[multiple] = false;',
				'\t\t}',
				'\t}',
				'',
				'\tList<Integer> result = new ArrayList<>();',
				'\tfor (int value = 2; value <= limit; value += 1) {',
				'\t\tif (prime[value]) {',
				'\t\t\tresult.add(value);',
				'\t\t}',
				'\t}',
				'\treturn result;',
				'}',
			].join('\n'),
		},
		{
			title: 'Breadth-First Search',
			code: [
				'private static List<String> bfsShortestPath(Map<String, List<String>> graph, String start, String goal) {',
				'\tQueue<String> queue = new ArrayDeque<>();',
				'\tMap<String, String> previous = new HashMap<>();',
				'\tqueue.add(start);',
				'\tprevious.put(start, null);',
				'',
				'\twhile (!queue.isEmpty()) {',
				'\t\tString node = queue.remove();',
				'\t\tif (node.equals(goal)) {',
				'\t\t\tbreak;',
				'\t\t}',
				'',
				'\t\tfor (String neighbor : graph.getOrDefault(node, List.of())) {',
				'\t\t\tif (previous.containsKey(neighbor)) {',
				'\t\t\t\tcontinue;',
				'\t\t\t}',
				'\t\t\tprevious.put(neighbor, node);',
				'\t\t\tqueue.add(neighbor);',
				'\t\t}',
				'\t}',
				'',
				'\tif (!previous.containsKey(goal)) {',
				'\t\treturn List.of();',
				'\t}',
				'',
				'\tList<String> path = new ArrayList<>();',
				'\tfor (String at = goal; at != null; at = previous.get(at)) {',
				'\t\tpath.add(at);',
				'\t}',
				'\tCollections.reverse(path);',
				'\treturn path;',
				'}',
			].join('\n'),
		},
	]),
	createPack('cpp', 'C++', 'cpp', '.cpp', ['cpp', 'cc', 'cxx', 'h', 'hpp'], [
		{
			title: 'Binary Search',
			code: [
				'int binarySearch(const std::vector<int>& sorted, int target) {',
				'\tint left = 0;',
				'\tint right = static_cast<int>(sorted.size()) - 1;',
				'',
				'\twhile (left <= right) {',
				'\t\tint mid = left + (right - left) / 2;',
				'\t\tif (sorted[mid] == target) { return mid; }',
				'\t\tif (sorted[mid] < target) { left = mid + 1; }',
				'\t\telse { right = mid - 1; }',
				'\t}',
				'',
				'\treturn -1;',
				'}',
			].join('\n'),
		},
		{
			title: 'Sieve of Eratosthenes',
			code: [
				'std::vector<int> sieveOfEratosthenes(int limit) {',
				'\tstd::vector<bool> prime(static_cast<size_t>(limit + 1), true);',
				'\tif (limit >= 0) { prime[0] = false; }',
				'\tif (limit >= 1) { prime[1] = false; }',
				'',
				'\tfor (int value = 2; value * value <= limit; value += 1) {',
				'\t\tif (!prime[static_cast<size_t>(value)]) { continue; }',
				'\t\tfor (int multiple = value * value; multiple <= limit; multiple += value) {',
				'\t\t\tprime[static_cast<size_t>(multiple)] = false;',
				'\t\t}',
				'\t}',
				'',
				'\tstd::vector<int> result;',
				'\tfor (int value = 2; value <= limit; value += 1) {',
				'\t\tif (prime[static_cast<size_t>(value)]) { result.push_back(value); }',
				'\t}',
				'\treturn result;',
				'}',
			].join('\n'),
		},
		{
			title: 'Breadth-First Search',
			code: [
				'std::vector<std::string> bfsShortestPath(',
				'\tconst std::unordered_map<std::string, std::vector<std::string>>& graph,',
				'\tconst std::string& start,',
				'\tconst std::string& goal',
				') {',
				'\tstd::queue<std::string> queue;',
				'\tstd::unordered_map<std::string, std::string> previous;',
				'\tstd::unordered_set<std::string> seen;',
				'\tqueue.push(start);',
				'\tseen.insert(start);',
				'\tprevious[start] = "";',
				'',
				'\twhile (!queue.empty()) {',
				'\t\tstd::string node = queue.front();',
				'\t\tqueue.pop();',
				'\t\tif (node == goal) { break; }',
				'',
				'\t\tauto iterator = graph.find(node);',
				'\t\tif (iterator == graph.end()) { continue; }',
				'\t\tfor (const std::string& neighbor : iterator->second) {',
				'\t\t\tif (seen.contains(neighbor)) { continue; }',
				'\t\t\tseen.insert(neighbor);',
				'\t\t\tprevious[neighbor] = node;',
				'\t\t\tqueue.push(neighbor);',
				'\t\t}',
				'\t}',
				'',
				'\tif (!seen.contains(goal)) { return {}; }',
				'',
				'\tstd::vector<std::string> path;',
				'\tfor (std::string at = goal; !at.empty(); at = previous[at]) {',
				'\t\tpath.push_back(at);',
				'\t}',
				'\tstd::reverse(path.begin(), path.end());',
				'\treturn path;',
				'}',
			].join('\n'),
		},
	]),
	createPack('csharp', 'C#', 'csharp', '.cs', ['cs'], [
		{
			title: 'Binary Search',
			code: [
				'static int BinarySearch(int[] sorted, int target)',
				'{',
				'\tint left = 0;',
				'\tint right = sorted.Length - 1;',
				'',
				'\twhile (left <= right)',
				'\t{',
				'\t\tint mid = left + (right - left) / 2;',
				'\t\tif (sorted[mid] == target) { return mid; }',
				'\t\tif (sorted[mid] < target) { left = mid + 1; }',
				'\t\telse { right = mid - 1; }',
				'\t}',
				'',
				'\treturn -1;',
				'}',
			].join('\n'),
		},
		{
			title: 'Sieve of Eratosthenes',
			code: [
				'static List<int> SieveOfEratosthenes(int limit)',
				'{',
				'\tvar prime = Enumerable.Repeat(true, limit + 1).ToArray();',
				'\tif (limit >= 0) { prime[0] = false; }',
				'\tif (limit >= 1) { prime[1] = false; }',
				'',
				'\tfor (int value = 2; value * value <= limit; value += 1)',
				'\t{',
				'\t\tif (!prime[value]) { continue; }',
				'\t\tfor (int multiple = value * value; multiple <= limit; multiple += value)',
				'\t\t{',
				'\t\t\tprime[multiple] = false;',
				'\t\t}',
				'\t}',
				'',
				'\tvar result = new List<int>();',
				'\tfor (int value = 2; value <= limit; value += 1)',
				'\t{',
				'\t\tif (prime[value]) { result.Add(value); }',
				'\t}',
				'\treturn result;',
				'}',
			].join('\n'),
		},
		{
			title: 'Breadth-First Search',
			code: [
				'static List<string> BfsShortestPath(Dictionary<string, List<string>> graph, string start, string goal)',
				'{',
				'\tvar queue = new Queue<string>();',
				'\tvar previous = new Dictionary<string, string?>();',
				'\tqueue.Enqueue(start);',
				'\tprevious[start] = null;',
				'',
				'\twhile (queue.Count > 0)',
				'\t{',
				'\t\tvar node = queue.Dequeue();',
				'\t\tif (node == goal) { break; }',
				'',
				'\t\tforeach (var neighbor in graph.GetValueOrDefault(node, new List<string>()))',
				'\t\t{',
				'\t\t\tif (previous.ContainsKey(neighbor)) { continue; }',
				'\t\t\tprevious[neighbor] = node;',
				'\t\t\tqueue.Enqueue(neighbor);',
				'\t\t}',
				'\t}',
				'',
				'\tif (!previous.ContainsKey(goal)) { return new List<string>(); }',
				'',
				'\tvar path = new List<string>();',
				'\tfor (string? at = goal; at is not null; at = previous[at])',
				'\t{',
				'\t\tpath.Add(at);',
				'\t}',
				'\tpath.Reverse();',
				'\treturn path;',
				'}',
			].join('\n'),
		},
	]),
	createPack('go', 'Go', 'go', '.go', ['go'], [
		{
			title: 'Binary Search',
			code: [
				'func binarySearch(sorted []int, target int) int {',
				'\tleft, right := 0, len(sorted)-1',
				'\tfor left <= right {',
				'\t\tmid := left + (right-left)/2',
				'\t\tif sorted[mid] == target {',
				'\t\t\treturn mid',
				'\t\t}',
				'\t\tif sorted[mid] < target {',
				'\t\t\tleft = mid + 1',
				'\t\t} else {',
				'\t\t\tright = mid - 1',
				'\t\t}',
				'\t}',
				'\treturn -1',
				'}',
			].join('\n'),
		},
		{
			title: 'Sieve of Eratosthenes',
			code: [
				'func sieveOfEratosthenes(limit int) []int {',
				'\tprime := make([]bool, limit+1)',
				'\tfor i := range prime {',
				'\t\tprime[i] = true',
				'\t}',
				'\tif limit >= 0 {',
				'\t\tprime[0] = false',
				'\t}',
				'\tif limit >= 1 {',
				'\t\tprime[1] = false',
				'\t}',
				'\tfor value := 2; value*value <= limit; value++ {',
				'\t\tif !prime[value] {',
				'\t\t\tcontinue',
				'\t\t}',
				'\t\tfor multiple := value * value; multiple <= limit; multiple += value {',
				'\t\t\tprime[multiple] = false',
				'\t\t}',
				'\t}',
				'\tresult := make([]int, 0)',
				'\tfor value := 2; value <= limit; value++ {',
				'\t\tif prime[value] {',
				'\t\t\tresult = append(result, value)',
				'\t\t}',
				'\t}',
				'\treturn result',
				'}',
			].join('\n'),
		},
		{
			title: 'Breadth-First Search',
			code: [
				'func bfsShortestPath(graph map[string][]string, start string, goal string) []string {',
				'\tqueue := []string{start}',
				'\tprevious := map[string]string{start: ""}',
				'\tseen := map[string]bool{start: true}',
				'',
				'\tfor head := 0; head < len(queue); head++ {',
				'\t\tnode := queue[head]',
				'\t\tif node == goal {',
				'\t\t\tbreak',
				'\t\t}',
				'',
				'\t\tfor _, neighbor := range graph[node] {',
				'\t\t\tif seen[neighbor] {',
				'\t\t\t\tcontinue',
				'\t\t\t}',
				'\t\t\tseen[neighbor] = true',
				'\t\t\tprevious[neighbor] = node',
				'\t\t\tqueue = append(queue, neighbor)',
				'\t\t}',
				'\t}',
				'',
				'\tif !seen[goal] {',
				'\t\treturn []string{}',
				'\t}',
				'',
				'\tpath := make([]string, 0)',
				'\tfor at := goal; at != ""; at = previous[at] {',
				'\t\tpath = append(path, at)',
				'\t}',
				'',
				'\tfor left, right := 0, len(path)-1; left < right; left, right = left+1, right-1 {',
				'\t\tpath[left], path[right] = path[right], path[left]',
				'\t}',
				'\treturn path',
				'}',
			].join('\n'),
		},
	]),
	createPack('rust', 'Rust', 'rust', '.rs', ['rs'], [
		{
			title: 'Binary Search',
			code: [
				'fn binary_search(sorted: &[i32], target: i32) -> i32 {',
				'\tlet mut left: i32 = 0;',
				'\tlet mut right: i32 = sorted.len() as i32 - 1;',
				'',
				'\twhile left <= right {',
				'\t\tlet mid = left + (right - left) / 2;',
				'\t\tlet value = sorted[mid as usize];',
				'\t\tif value == target {',
				'\t\t\treturn mid;',
				'\t\t}',
				'\t\tif value < target {',
				'\t\t\tleft = mid + 1;',
				'\t\t} else {',
				'\t\t\tright = mid - 1;',
				'\t\t}',
				'\t}',
				'',
				'\t-1',
				'}',
			].join('\n'),
		},
		{
			title: 'Sieve of Eratosthenes',
			code: [
				'fn sieve_of_eratosthenes(limit: usize) -> Vec<usize> {',
				'\tlet mut prime = vec![true; limit + 1];',
				'\tif limit >= 0 { prime[0] = false; }',
				'\tif limit >= 1 { prime[1] = false; }',
				'',
				'\tlet mut value = 2;',
				'\twhile value * value <= limit {',
				'\t\tif prime[value] {',
				'\t\t\tlet mut multiple = value * value;',
				'\t\t\twhile multiple <= limit {',
				'\t\t\t\tprime[multiple] = false;',
				'\t\t\t\tmultiple += value;',
				'\t\t\t}',
				'\t\t}',
				'\t\tvalue += 1;',
				'\t}',
				'',
				'\tlet mut result = Vec::new();',
				'\tfor value in 2..=limit {',
				'\t\tif prime[value] {',
				'\t\t\tresult.push(value);',
				'\t\t}',
				'\t}',
				'\tresult',
				'}',
			].join('\n'),
		},
		{
			title: 'Breadth-First Search',
			code: [
				'fn bfs_shortest_path(',
				'\tgraph: &std::collections::HashMap<String, Vec<String>> ,',
				'\tstart: &str,',
				'\tgoal: &str',
				') -> Vec<String> {',
				'\tlet mut queue = std::collections::VecDeque::new();',
				'\tlet mut previous: std::collections::HashMap<String, String> = std::collections::HashMap::new();',
				'\tlet mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();',
				'\tqueue.push_back(start.to_string());',
				'\tseen.insert(start.to_string());',
				'\tprevious.insert(start.to_string(), String::new());',
				'',
				'\twhile let Some(node) = queue.pop_front() {',
				'\t\tif node == goal {',
				'\t\t\tbreak;',
				'\t\t}',
				'',
				'\t\tif let Some(neighbors) = graph.get(&node) {',
				'\t\t\tfor neighbor in neighbors {',
				'\t\t\t\tif seen.contains(neighbor) {',
				'\t\t\t\t\tcontinue;',
				'\t\t\t\t}',
				'\t\t\t\tseen.insert(neighbor.clone());',
				'\t\t\t\tprevious.insert(neighbor.clone(), node.clone());',
				'\t\t\t\tqueue.push_back(neighbor.clone());',
				'\t\t\t}',
				'\t\t}',
				'\t}',
				'',
				'\tif !seen.contains(goal) {',
				'\t\treturn Vec::new();',
				'\t}',
				'',
				'\tlet mut path = Vec::new();',
				'\tlet mut at = goal.to_string();',
				'\twhile !at.is_empty() {',
				'\t\tpath.push(at.clone());',
				'\t\tat = previous.get(&at).cloned().unwrap_or_default();',
				'\t}',
				'\tpath.reverse();',
				'\tpath',
				'}',
			].join('\n'),
		},
	]),
];

function createPack(
	key: string,
	label: string,
	languageId: string,
	extension: string,
	workspaceExtensions: string[],
	algorithms: RawAlgorithmSnippet[]
): LanguageSnippetPack {
	const commentToken = getCommentToken(languageId);

	return {
		key,
		label,
		languageId,
		extension,
		workspaceExtensions,
		snippets: algorithms.map((algorithm) => ({
			title: algorithm.title,
			prefixLines: [
				`${commentToken} Famous algorithm practice: ${algorithm.title}`,
				'',
			],
			typedBlock: algorithm.code,
			suffixLines: [],
		})),
	};
}

function getCommentToken(languageId: string): string {
	if (languageId === 'python') {
		return '#';
	}

	return '//';
}
